<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="16" passed="13">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="73709" started-at="2016-07-15T18:14:35Z" finished-at="2016-07-15T18:15:49Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="73709" started-at="2016-07-15T18:14:35Z" finished-at="2016-07-15T18:15:49Z">
      <class name="com.griggi.app.MainTest">
        <test-method status="PASS" signature="beforeTest(org.testng.ITestContext)[pri:0, instance:com.griggi.app.MainTest@50431425]" name="beforeTest" is-config="true" duration-ms="13942" started-at="2016-07-15T23:44:35Z" finished-at="2016-07-15T23:44:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@23406fd7]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="loginBad1()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="loginBad1" duration-ms="1986" started-at="2016-07-15T23:44:49Z" description="Logging in. - Too long" finished-at="2016-07-15T23:44:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginBad1 -->
        <test-method status="PASS" signature="loginBad2()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="loginBad2" duration-ms="1144" started-at="2016-07-15T23:44:51Z" description="Logging in. - Too short" finished-at="2016-07-15T23:44:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginBad2 -->
        <test-method status="PASS" signature="loginBad3()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="loginBad3" duration-ms="1147" started-at="2016-07-15T23:44:53Z" description="Logging in. - Invalid" finished-at="2016-07-15T23:44:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginBad3 -->
        <test-method status="FAIL" signature="loginGood2()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="loginGood2" duration-ms="2454" started-at="2016-07-15T23:44:54Z" description="Verifies that after a bad login, user can enter" finished-at="2016-07-15T23:44:56Z">
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<[The password you entered is not valid.]> but was:<[]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<[The password you entered is not valid.]> but was:<[]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.griggi.app.MainTest.loginGood2(MainTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginGood2 -->
        <test-method status="PASS" signature="loginGood1()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="loginGood1" duration-ms="2393" started-at="2016-07-15T23:44:56Z" description="Logging in. - GOOD" finished-at="2016-07-15T23:44:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginGood1 -->
        <test-method status="PASS" signature="dashboardUICheck1()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="dashboardUICheck1" duration-ms="136" started-at="2016-07-15T23:44:59Z" description="Check Dashboard UI - 1 (Nav)" finished-at="2016-07-15T23:44:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dashboardUICheck1 -->
        <test-method status="PASS" signature="dashboardUICheck2()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="dashboardUICheck2" duration-ms="19" started-at="2016-07-15T23:44:59Z" description="Check Dashboard UI - 2 (Widgets)" finished-at="2016-07-15T23:44:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dashboardUICheck2 -->
        <test-method status="PASS" signature="dashboardUICheck3()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="dashboardUICheck3" duration-ms="28" started-at="2016-07-15T23:44:59Z" description="Check Dashboard UI - 3 (Header)" finished-at="2016-07-15T23:44:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dashboardUICheck3 -->
        <test-method status="PASS" signature="verifyLatestNodeURL()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="verifyLatestNodeURL" duration-ms="787" started-at="2016-07-15T23:44:59Z" description="Verify the url for the lastest node on dashboard" finished-at="2016-07-15T23:45:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLatestNodeURL -->
        <test-method status="PASS" signature="listOfNodes()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="listOfNodes" duration-ms="206" started-at="2016-07-15T23:45:00Z" description="Verify Nav from database - List of nodes" finished-at="2016-07-15T23:45:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listOfNodes -->
        <test-method status="FAIL" signature="nodeAdminDropdownArrow()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="nodeAdminDropdownArrow" duration-ms="15" started-at="2016-07-15T23:45:00Z" description="Admin node arrow exists" finished-at="2016-07-15T23:45:00Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.griggi.app.MainTest.nodeAdminDropdownArrow(MainTest.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nodeAdminDropdownArrow -->
        <test-method status="PASS" signature="routerSpeed()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="routerSpeed" duration-ms="7434" started-at="2016-07-15T23:45:00Z" description="Router Speed" finished-at="2016-07-15T23:45:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- routerSpeed -->
        <test-method status="PASS" signature="availableQuota()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="availableQuota" duration-ms="7937" started-at="2016-07-15T23:45:07Z" description="Checks the available quota of the user with the DB" finished-at="2016-07-15T23:45:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- availableQuota -->
        <test-method status="PASS" signature="dataSharing()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="dataSharing" duration-ms="20309" started-at="2016-07-15T23:45:15Z" description="Tests the data sharing feature" finished-at="2016-07-15T23:45:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataSharing -->
        <test-method status="FAIL" signature="routerFUPLimit()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="routerFUPLimit" duration-ms="5010" started-at="2016-07-15T23:45:36Z" description="Tests the router fup limit shown to user in dashboard" finished-at="2016-07-15T23:45:41Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<0.31> but was:<0.17>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<0.31> but was:<0.17>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at com.griggi.app.MainTest.routerFUPLimit(MainTest.java:457)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- routerFUPLimit -->
        <test-method status="PASS" signature="dataRecieved()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="dataRecieved" duration-ms="8093" started-at="2016-07-15T23:45:41Z" description="Checks the data that has been shared to the user on all the nodes" finished-at="2016-07-15T23:45:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataRecieved -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.griggi.app.MainTest@50431425]" name="afterTest" is-config="true" duration-ms="377" started-at="2016-07-15T23:45:49Z" finished-at="2016-07-15T23:45:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.griggi.app.MainTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
