<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="22" passed="18">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="74444" started-at="2016-07-16T18:21:55Z" finished-at="2016-07-16T18:23:10Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="74444" started-at="2016-07-16T18:21:55Z" finished-at="2016-07-16T18:23:10Z">
      <class name="com.griggi.app.MainTest">
        <test-method status="PASS" signature="beforeTest(org.testng.ITestContext)[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="beforeTest" is-config="true" duration-ms="2634" started-at="2016-07-16T23:51:55Z" finished-at="2016-07-16T23:51:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@69bff825]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="loginBad1()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="loginBad1" duration-ms="1405" started-at="2016-07-16T23:51:58Z" description="Logging in. - Too long" finished-at="2016-07-16T23:51:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginBad1 -->
        <test-method status="PASS" signature="loginBad2()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="loginBad2" duration-ms="1028" started-at="2016-07-16T23:51:59Z" description="Logging in. - Too short" finished-at="2016-07-16T23:52:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginBad2 -->
        <test-method status="PASS" signature="loginBad3()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="loginBad3" duration-ms="1117" started-at="2016-07-16T23:52:00Z" description="Logging in. - Invalid" finished-at="2016-07-16T23:52:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginBad3 -->
        <test-method status="FAIL" signature="loginGood2()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="loginGood2" duration-ms="2191" started-at="2016-07-16T23:52:01Z" description="Verifies that after a bad login, user can enter" finished-at="2016-07-16T23:52:04Z">
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<[The password you entered is not valid.]> but was:<[]>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<[The password you entered is not valid.]> but was:<[]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.griggi.app.MainTest.loginGood2(MainTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginGood2 -->
        <test-method status="PASS" signature="loginGood1()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="loginGood1" duration-ms="2201" started-at="2016-07-16T23:52:04Z" description="Logging in. - GOOD" finished-at="2016-07-16T23:52:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginGood1 -->
        <test-method status="PASS" signature="dashboardUICheck1()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="dashboardUICheck1" duration-ms="86" started-at="2016-07-16T23:52:06Z" description="Check Dashboard UI - 1 (Nav)" finished-at="2016-07-16T23:52:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dashboardUICheck1 -->
        <test-method status="PASS" signature="dashboardUICheck2()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="dashboardUICheck2" duration-ms="21" started-at="2016-07-16T23:52:06Z" description="Check Dashboard UI - 2 (Widgets)" finished-at="2016-07-16T23:52:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dashboardUICheck2 -->
        <test-method status="PASS" signature="dashboardUICheck3()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="dashboardUICheck3" duration-ms="25" started-at="2016-07-16T23:52:06Z" description="Check Dashboard UI - 3 (Header)" finished-at="2016-07-16T23:52:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dashboardUICheck3 -->
        <test-method status="PASS" signature="verifyLatestNodeURL()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="verifyLatestNodeURL" duration-ms="226" started-at="2016-07-16T23:52:06Z" description="Verify the url for the lastest node on dashboard" finished-at="2016-07-16T23:52:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLatestNodeURL -->
        <test-method status="PASS" signature="listOfNodes()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="listOfNodes" duration-ms="526" started-at="2016-07-16T23:52:06Z" description="Verify Nav from database - List of nodes" finished-at="2016-07-16T23:52:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- listOfNodes -->
        <test-method status="FAIL" signature="nodeAdminDropdownArrow()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="nodeAdminDropdownArrow" duration-ms="25" started-at="2016-07-16T23:52:07Z" description="Admin node arrow exists" finished-at="2016-07-16T23:52:07Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at com.griggi.app.MainTest.nodeAdminDropdownArrow(MainTest.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nodeAdminDropdownArrow -->
        <test-method status="PASS" signature="routerSpeed()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="routerSpeed" duration-ms="6984" started-at="2016-07-16T23:52:07Z" description="Router Speed" finished-at="2016-07-16T23:52:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- routerSpeed -->
        <test-method status="PASS" signature="availableQuota()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="availableQuota" duration-ms="7287" started-at="2016-07-16T23:52:14Z" description="Checks the available quota of the user with the DB" finished-at="2016-07-16T23:52:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- availableQuota -->
        <test-method status="PASS" signature="dataSharing()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="dataSharing" duration-ms="15427" started-at="2016-07-16T23:52:21Z" description="Tests the data sharing feature" finished-at="2016-07-16T23:52:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataSharing -->
        <test-method status="PASS" signature="routerFUPLimit()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="routerFUPLimit" duration-ms="7088" started-at="2016-07-16T23:52:37Z" description="Tests the router fup limit shown to user in dashboard" finished-at="2016-07-16T23:52:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- routerFUPLimit -->
        <test-method status="PASS" signature="dataRecieved()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="dataRecieved" duration-ms="7995" started-at="2016-07-16T23:52:44Z" description="Checks the data that has been shared to the user on all the nodes" finished-at="2016-07-16T23:52:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataRecieved -->
        <test-method status="FAIL" signature="dataShared()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="dataShared" duration-ms="1490" started-at="2016-07-16T23:52:52Z" description="Tests the data shared by USERNAME to other users" finished-at="2016-07-16T23:52:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<0.0> but was:<0.93>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<0.0> but was:<0.93>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at com.griggi.app.MainTest.dataShared(MainTest.java:851)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataShared -->
        <test-method status="PASS" signature="dataSharingReduction()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="dataSharingReduction" duration-ms="9573" started-at="2016-07-16T23:52:53Z" description="Checks whether the user cannot reduce the data shared to user beyond what is available with them" finished-at="2016-07-16T23:53:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataSharingReduction -->
        <test-method status="PASS" signature="dataTopUpUI1()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="dataTopUpUI1" duration-ms="4966" started-at="2016-07-16T23:53:03Z" description="Tests the UI for the data topup page - I" finished-at="2016-07-16T23:53:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataTopUpUI1 -->
        <test-method status="PASS" signature="dataTopUpUI2()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="dataTopUpUI2" duration-ms="25" started-at="2016-07-16T23:53:08Z" description="Tests the UI for the data topup page - II" finished-at="2016-07-16T23:53:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataTopUpUI2 -->
        <test-method status="PASS" signature="dataTopUpUI3()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="dataTopUpUI3" duration-ms="20" started-at="2016-07-16T23:53:08Z" description="Tests the UI for the data topup page - III" finished-at="2016-07-16T23:53:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataTopUpUI3 -->
        <test-method status="FAIL" signature="dataTopUpInput()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="dataTopUpInput" duration-ms="1501" started-at="2016-07-16T23:53:08Z" description="Tests the UI for the data topup page - Input (Invalid)" finished-at="2016-07-16T23:53:09Z">
          <exception class="java.lang.ArrayIndexOutOfBoundsException">
            <message>
              <![CDATA[2]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 2
	at com.griggi.app.MainTest.dataTopUpInput(MainTest.java:895)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArrayIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dataTopUpInput -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.griggi.app.MainTest@247db9bc]" name="afterTest" is-config="true" duration-ms="413" started-at="2016-07-16T23:53:09Z" finished-at="2016-07-16T23:53:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.griggi.app.MainTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
